### ISSUE TITLE
Import Error - No module named tutorial

### ISSUE THREAD

**Issue by samlo20** [gnuradio/gr-tutorial#12]
Hello I tried to run the example mpsk_stage6.grc and there was an error called importerror
because there is no module named tutorial

Is there any way to resolve this issue?

**Comment by tuklimanice13** [comment]
copy the module in the /usr/local/lib64/python2.7/site-packages/tutorial to /usr/lib64/python2.7/site-packages/tutorial with your terminal

``sudo cp -r /usr/local/lib64/python2.7/site-packages/tutorial  /usr/lib64/python2.7/site-packages/tutorial

**Comment by jn9531** [comment]
Hello, I tried to run the example mpsk_stage6.grc and there was an error MIssing Block tutorial_my_qpsk_demod_cb_1

what should I do?
