### ISSUE TITLE
File transfer using MPSK

### ISSUE THREAD

**Issue by kkumar1234** [gnuradio/gr-tutorial#13]
Hi,

I am trying to implement file transfer using MPSK as per examples 7/mpsk_stage6.grc.

However, at the receiver end, I am not getting any output.

Please find attached Tx and Rx flow graph.
Please let me know if I am missing anything.

Thanks
Kailash 
![rx](https://user-images.githubusercontent.com/21056664/38495484-5e79cbce-3c17-11e8-9009-a31535d0a38d.png)
![tx](https://user-images.githubusercontent.com/21056664/38495485-5eac823a-3c17-11e8-82a9-8406ef18c60d.png)

**Comment by marcusmueller** [comment]
Closing, as this is a bug tanker and what you seem to be reporting is not inherently a bug -please feel encouraged to register for and peruse the discuss-gnuradio@gnu.org mailing list!
